3.x
digitalbazaar/bedrock-key-http pull request #5
Opened 2018-05-27 16:03 UTC by mattcollier

Depends on:

1. https://github.com/digitalbazaar/bedrock-key/pull/11
2. https://github.com/digitalbazaar/bedrock-passport/pull/25

2018-05-28 16:44 UTC, dlongley requested changes
Will review more when I can, just wanted to note that we should base this against the `account` changes so as to reduce revs.

2018-05-28 16:44 UTC, dlongley commented on lib/index.js
> +        {actor: req.user.identity, publicKey, privateKey}, err => {
All of these will need to change to:

```{actor: req.user.actor, ...```

Once https://github.com/digitalbazaar/bedrock-passport/pull/24 is merged.

2018-06-14 22:30 UTC, dlongley commented
Also depends on: https://github.com/digitalbazaar/bedrock-passport/pull/24

2018-06-15 02:21 UTC, davidlehn commented on lib/index.js
> +const logger = bedrock.loggers.get('app');
Use a child logger.

2022-05-27 19:48 UTC, closed without merging